print("hello world")
a=input("enter a integer value for a: ")
b=input("enter a integer value for b: ")
print(type(a))
print(type(b))
a=int(a)
b=int(b)
print(type(a))
print(type(b))   #gives the type of the value (int,string,float)
print(a+b)
print("End basics")
c=(str(1))
print(type(c))